### ISSUE TITLE
[Errno 8] Exec format error

### ISSUE THREAD

**Issue by santamaiti** [ManiAm/VENTOS_Public#2]
Hi ManiAm,

The steps are really helpful. Everything worked fine for me. Only in last part, when I run sumo, it's throwing a runtime error. Could you please suggest.

 -1
 1452387204
 1452387204
 Could not start SUMO (/home/santa/Desktop/workspace/VENTOS_Public/sumoBinary/sumo-guiD -c 6hello.sumo.cfg): [Errno 8] Exec format error
 <![CDATA[]]>
 <![CDATA[]]>

Regards,

**Comment by ManiAm** [comment]
Hi,

1. Did VENTOS ask you to download the SUMO executable upon the first run?
2. Can you verify that there are two SUMO binaries in the VENTOS_Public/sumoBinary folder?
3. Is the path "/home/santa/Desktop/workspace/VENTOS_Public/sumoBinary/" correct?
4. Are you using Ubuntu 14? Since the SUMO binaries are compiled/built under Ubuntu 14
5. Can you double check that you have installed all the required libraries (step 1 under import VENTOS section)

**Comment by santamaiti** [comment]
Hi ManiAm,

Thanks for your guidance. The problem was that, I was working in Ubuntu 14 of 32 bit, so the sumo binaries was not working. Now, I've tried in Ubuntu 14, 64bit and it is working fine.
