### ISSUE TITLE
Simulation Issues

### ISSUE THREAD

**Issue by TheRealJRi** [ManiAm/VENTOS_Public#22]
Hi there, my team and I are conducting a project that calls for a simulation that VENTOS provides. With that being said, we are all undergrads and have limited knowledge using Ubuntu and VENTOS. Anyways, we have downloaded the VENTOS on Ubuntu version 16.04 and followed the exact steps laid out by the YouTube video as well as the User Manual. The Install was successful until we had gotten into the IDE where some of the folders were "cut out" (sorry for not knowing the exact terminology, a photo will be added to show what I am talking about). This, I believe lead to the simulation being different than what was shown on the YouTube video and a rather wanky "Run-Configuration" portion of the set-up. Is there a common error we are making for this mistake to happen? Any help would be greatly appreciated. Thank you for your time. 

![screenshot from 2018-04-10 20-47-53](https://user-images.githubusercontent.com/38264757/38590659-9f50719a-3d00-11e8-9a52-0be8a3801603.png)
  

![screenshot from 2018-04-10 20-48-32](https://user-images.githubusercontent.com/38264757/38590661-a3ac9174-3d00-11e8-9d67-83ca586b7146.png)

**Comment by ManiAm** [comment]
>> until we had gotten into the IDE where some of the folders were "cut out"

This is normal. It means those folder are not part of the build, since they do not have any source files.

>> Is there a common error we are making for this mistake to happen?

From the picture above, I can see that you are running the scenarios successfully.

>> This, I believe lead to the simulation being different than what was shown on the YouTube video

The scenario that is very close to the uploaded video is this:

https://github.com/ManiAm/VENTOS_Public/blob/00bf82365cc992c90422b771b59090ce1f471317/examples/platoon_management/omnetpp.ini#L36
